name: Build • Test • Package • Release

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure (CMake)
        run: cmake -S . -B build -D BUILD_NUMBER=${BUILD_NUMBER} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -- -j2

      - name: Test (CTest)
        run: ctest --test-dir build --output-on-failure

      - name: Package (.deb via CPack)
        run: |
          cd build
          cpack

      - name: Upload artifact (.deb)
        uses: actions/upload-artifact@v4
        with:
          name: helloworld-deb
          path: build/*.deb

      - name: Create GitHub Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.deb