name: Build

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build-test-package:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:20.04
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Install build tools in container
        run: |
          apt-get update
          apt-get install -y git ca-certificates cmake build-essential

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake)
        run: cmake -S homework_1 -B build -D BUILD_NUMBER=${BUILD_NUMBER} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -- -j2

      - name: Test (CTest)
        run: ctest --test-dir build --output-on-failure

      - name: Package (.deb via CPack)
        run: cpack --config build/CPackConfig.cmake

      - name: Upload artifact (.deb)
        uses: actions/upload-artifact@v4
        with:
          name: helloworld-deb
          path: helloworld-0.0.${{ env.BUILD_NUMBER }}-Linux.deb

      - name: Create GitHub Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: helloworld-0.0.${{ env.BUILD_NUMBER }}-Linux.deb
