name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Create build directory
      run: mkdir build
    
    - name: Configure CMake
      run: cmake -B build -S homework_1
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Test
      run: |
        if [ -f build/test ]; then
          ./build/test
        else
          echo "No tests found"
        fi
